In [6]:
import nltk
import string
import re

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [7]:
texto_original = """Algoritmos de aprendizado supervisionado utilizam dados coletados. A partir dos dados coletados, 
                    um conjunto de características é extraído. As características podem ser estruturais ou estatísticas. 
                    As características estruturais estabelecem relações entre os dados, enquanto que as estatísticas 
                    são características quantitativas. A partir das características, os modelos de aprendizado de 
                    máquina são construídos para o reconhecimento de atividades humanas."""
texto_original

'Algoritmos de aprendizado supervisionado utilizam dados coletados. A partir dos dados coletados, \n                    um conjunto de características é extraído. As características podem ser estruturais ou estatísticas. \n                    As características estruturais estabelecem relações entre os dados, enquanto que as estatísticas \n                    são características quantitativas. A partir das características, os modelos de aprendizado de \n                    máquina são construídos para o reconhecimento de atividades humanas.'

In [8]:
texto_original = re.sub(r'\s+',' ',texto_original)
texto_original

'Algoritmos de aprendizado supervisionado utilizam dados coletados. A partir dos dados coletados, um conjunto de características é extraído. As características podem ser estruturais ou estatísticas. As características estruturais estabelecem relações entre os dados, enquanto que as estatísticas são características quantitativas. A partir das características, os modelos de aprendizado de máquina são construídos para o reconhecimento de atividades humanas.'

In [9]:
def converte_para_minusculas (texto):
    return texto.lower()

In [10]:
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words("portuguese")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kaiov\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
def remove_stopwords (texto):
    texto_formatado = converte_para_minusculas(texto)
    tokens = [] # lista de tokens
    for token in nltk.word_tokenize(texto_formatado): # token é cada uma das palavras
        tokens.append(token) # insere na lista de tokens
    tokens = [cada_token for cada_token in tokens if cada_token not in stopwords and cada_token not in string.punctuation] 
    texto_formatado = ' '.join([str(cada_token) for cada_token in tokens if not cada_token.isdigit()])
    return texto_formatado   

In [12]:
texto_formatado = remove_stopwords(texto_original)
texto_formatado

'algoritmos aprendizado supervisionado utilizam dados coletados partir dados coletados conjunto características extraído características podem ser estruturais estatísticas características estruturais estabelecem relações dados enquanto estatísticas características quantitativas partir características modelos aprendizado máquina construídos reconhecimento atividades humanas'

In [13]:
frequencia_palavras = nltk.FreqDist(nltk.word_tokenize(texto_formatado))
frequencia_palavras

FreqDist({'características': 5, 'dados': 3, 'aprendizado': 2, 'coletados': 2, 'partir': 2, 'estruturais': 2, 'estatísticas': 2, 'algoritmos': 1, 'supervisionado': 1, 'utilizam': 1, ...})

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
documento = ['Algoritmos de aprendizados supervisionados utilizam dados coletados.',
'A partir dos dado coletado, conjunto de características é extraído.',
'As características podem ser estruturais ou estatísticas.',
'As características estruturais estabelecem relações entre os dados, enquanto que as estatísticas são características quantitativas.',
'A partir das características, os modelos de aprendizado de máquina são construídos para o reconhecimento de atividades humanas.']

In [20]:
vetorizador = CountVectorizer(documento, binary=True, stop_words=['de','das','as','ou','dos'], min_df=2, max_df=0.85)
BoW = vetorizador.fit_transform(documento)
vetorizador.vocabulary_
#BoW.shape


{'dados': 1,
 'partir': 5,
 'características': 0,
 'estruturais': 3,
 'estatísticas': 2,
 'os': 4,
 'são': 6}

In [21]:
print(BoW.toarray())

[[0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0]
 [1 0 1 1 0 0 0]
 [1 1 1 1 1 0 1]
 [1 0 0 0 1 1 1]]


In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
vetorizador = TfidfVectorizer(documento, stop_words=['de','das','as','ou','dos'],min_df=2, max_df=0.8)
BoW = vetorizador.fit_transform(documento)
print(BoW.toarray())

[[0.         1.         0.         0.         0.         0.
  0.        ]
 [0.57252551 0.         0.         0.         0.         0.8198869
  0.        ]
 [0.44274009 0.         0.63402729 0.63402729 0.         0.
  0.        ]
 [0.52974084 0.37930849 0.37930849 0.37930849 0.37930849 0.
  0.37930849]
 [0.37391794 0.         0.         0.         0.53547032 0.53547032
  0.53547032]]
C:\Users\kaiov\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass input=['Algoritmos de aprendizados supervisionados utilizam dados coletados.', 'A partir dos dado coletado, conjunto de características é extraído.', 'As características podem ser estruturais ou estatísticas.', 'As características estruturais estabelecem relações entre os dados, enquanto que as estatísticas são características quantitativas.', 'A partir das características, os modelos de aprendizado de máquina são construídos para o reconhecimento de atividades humanas.'] as keyword args. From version 0.25 passing

In [27]:
vetor_palavras = []
for cada_palavra in nltk.word_tokenize(texto_formatado):
    vetor_palavras.append(cada_palavra)
vetor_palavras

['algoritmos',
 'aprendizado',
 'supervisionado',
 'utilizam',
 'dados',
 'coletados',
 'partir',
 'dados',
 'coletados',
 'conjunto',
 'características',
 'extraído',
 'características',
 'podem',
 'ser',
 'estruturais',
 'estatísticas',
 'características',
 'estruturais',
 'estabelecem',
 'relações',
 'dados',
 'enquanto',
 'estatísticas',
 'características',
 'quantitativas',
 'partir',
 'características',
 'modelos',
 'aprendizado',
 'máquina',
 'construídos',
 'reconhecimento',
 'atividades',
 'humanas']

In [31]:
def identifica_bigramas (texto):
    vetor_bigramas = []
    for i in range(0, len(texto)):
        if i == len(texto)-1:
            break
        else:
            cada_bigrama = texto[i] + ' > ' + texto [i+1]
    
    vetor_bigramas.append(cada_bigrama)
    return vetor_bigramas

In [30]:
vetor_bigramas = identifica_bigramas(vetor_palavras)
vetor_bigramas

['atividades > humanas']

In [33]:
from nltk.collocations import BigramCollocationFinder

In [34]:
medidas_bigramas = nltk.collocations.BigramAssocMeasures()

In [38]:
bigramas_encontrados = BigramCollocationFinder.from_words(nltk.word_tokenize(texto_formatado))
#bigramas_encontrados = nltk.FreqDist(nltk.bigrams(vetor_palavras))
bigramas_encontrados.apply_freq_filter(2)
bigramas_encontrados.nbest(medidas_bigramas.pmi, 5)


[('dados', 'coletados'), ('estatísticas', 'características')]